const SubwayList = [
"Bathurst",
"Bay",
// "Bayview",
// "Bessarion",
"Bloor-Yonge",
// "Broadview",
// "Castle Frank",
// "Chester",
// "Christie",
"College",
// "Coxwell",
// "Davisville",
// "Don Mills",
// "Donlands",
// "Downsview Park",
// "Dufferin",
"Dundas",
// "Dundas West",
"Dupont",
// "Eglinton",
// "Eglinton West",
// "Ellesmere",
// "Finch",
// "Finch West",
// "Glencairn",
// "Greenwood",
// "High Park",
// "Highway 407",
// "Islington",
// "Jane",
// "Keele",
// "Kennedy",
"King",
// "Kipling",
// "Lansdowne",
// "Lawrence",
// "Lawrence East",
// "Lawrence West",
// "Leslie",
// "Main Street",
// "McCowan",
// "Midland",
// "Museum",
// "North York Centre",
// "Old Mill",
// "Osgoode",
// "Ossington",
// "Pape",
// "Pioneer Village",
"Queen",
// "Queen's Park",
// "Rosedale",
// "Royal York",
// "Runnymede",
// "Scarborough Centre",
// "Sheppard-Yonge",
// "Sheppard West",
"Sherbourne",
"Spadina",
// "St Andrew",
"St Clair",
// "St Clair West",
"St George",
// "St Patrick",
// "Summerhill",
// "Union",
// "Vaughan Metropolitan Centre",
// "Victoria Park",
// "Warden",
"Wellesley",
// "Wilson",
// "Woodbine",
// "York Mills",
// "York University"
// "Yorkdale"
];

export default SubwayList;
